version: "3"

services:
  front:
    build: ./front
    container_name: food-app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./front/:/usr/app
      - react_node_modules:/usr/app/node_modules:delegated
    ports:
      - 3000:3000
    tty: true

volumes:
  react_node_modules: